// Generated by scripts/generate-passive-parts.py. Do not edit.
import type { ChipProps } from "@tscircuit/props"
import type { ReactElement } from "react"
import { CL10B103KB8NNNC } from "../imports/CL10B103KB8NNNC"
import { CL10B104KB8NNNC } from "../imports/CL10B104KB8NNNC"
import { CL10C102JB8NNNC } from "../imports/CL10C102JB8NNNC"
import { CL10C270JB8NNNC } from "../imports/CL10C270JB8NNNC"
import { CL10C332JB8NNNC } from "../imports/CL10C332JB8NNNC"
import { A_0603WAF0000T5E } from "../imports/A_0603WAF0000T5E"
import { A_0603WAF1504T5E } from "../imports/A_0603WAF1504T5E"
import { A_0603WAF1003T5E } from "../imports/A_0603WAF1003T5E"
import { A_0603WAF1802T5E } from "../imports/A_0603WAF1802T5E"
import { A_0603WAF1001T5E } from "../imports/A_0603WAF1001T5E"
import { A_0603WAF2201T5E } from "../imports/A_0603WAF2201T5E"
import { A_0603WAF2003T5E } from "../imports/A_0603WAF2003T5E"
import { A_0603WAF2002T5E } from "../imports/A_0603WAF2002T5E"
import { A_0603WAF2700T5E } from "../imports/A_0603WAF2700T5E"
import { A_0603WAF3301T5E } from "../imports/A_0603WAF3301T5E"
import { A_0603WAF3302T5E } from "../imports/A_0603WAF3302T5E"
import { A_0603WAF5101T5E } from "../imports/A_0603WAF5101T5E"
import { A_0603WAF5103T5E } from "../imports/A_0603WAF5103T5E"
import { A_0603WAF7501T5E } from "../imports/A_0603WAF7501T5E"
import { A_0603WAF8203T5E } from "../imports/A_0603WAF8203T5E"
import { A_0603WAF9102T5E } from "../imports/A_0603WAF9102T5E"
import { CL10B105KA8NNNC } from "../imports/CL10B105KA8NNNC"
import { CL10A106KO8NQNC } from "../imports/CL10A106KO8NQNC"
import { CL21A226KOQNNNE } from "../imports/CL21A226KOQNNNE"
import { CL32A107MQVNNNE } from "../imports/CL32A107MQVNNNE"
import { CL10C101JB8NNNC } from "../imports/CL10C101JB8NNNC"
import { CL10C331JB8NNNC } from "../imports/CL10C331JB8NNNC"
import { CL10C330JB8NNNC } from "../imports/CL10C330JB8NNNC"
import { FCC0603N470J500CT } from "../imports/FCC0603N470J500CT"
import { CL10C681JB8NNNC } from "../imports/CL10C681JB8NNNC"
import { RC0603FR_0710KL } from "../imports/RC0603FR_0710KL"
import { A_0603WAF150JT5E } from "../imports/A_0603WAF150JT5E"
import { A_0603WAF470JT5E } from "../imports/A_0603WAF470JT5E"

export function getPassiveElement({ key, name }: { key: string; name: string }): ReactElement<ChipProps> | undefined {
  switch (key) {
    case "cap-0.01u": return CL10B103KB8NNNC({ name })
    case "cap-0.1u": return CL10B104KB8NNNC({ name })
    case "cap-1000p": return CL10C102JB8NNNC({ name })
    case "cap-27p": return CL10C270JB8NNNC({ name })
    case "cap-3300p": return CL10C332JB8NNNC({ name })
    case "res-0": return A_0603WAF0000T5E({ name })
    case "res-1.5M": return A_0603WAF1504T5E({ name })
    case "res-100k": return A_0603WAF1003T5E({ name })
    case "res-18k": return A_0603WAF1802T5E({ name })
    case "res-1k": return A_0603WAF1001T5E({ name })
    case "res-2.2k": return A_0603WAF2201T5E({ name })
    case "res-200k": return A_0603WAF2003T5E({ name })
    case "res-20k": return A_0603WAF2002T5E({ name })
    case "res-270": return A_0603WAF2700T5E({ name })
    case "res-3.3k": return A_0603WAF3301T5E({ name })
    case "res-33k": return A_0603WAF3302T5E({ name })
    case "res-5.1k": return A_0603WAF5101T5E({ name })
    case "res-510k": return A_0603WAF5103T5E({ name })
    case "res-7.5k": return A_0603WAF7501T5E({ name })
    case "res-820k": return A_0603WAF8203T5E({ name })
    case "res-91k": return A_0603WAF9102T5E({ name })
    case "cap-1u": return CL10B105KA8NNNC({ name })
    case "cap-10u": return CL10A106KO8NQNC({ name })
    case "cap-22u": return CL21A226KOQNNNE({ name })
    case "cap-100u": return CL32A107MQVNNNE({ name })
    case "cap-100p": return CL10C101JB8NNNC({ name })
    case "cap-330p": return CL10C331JB8NNNC({ name })
    case "cap-33p": return CL10C330JB8NNNC({ name })
    case "cap-47p": return FCC0603N470J500CT({ name })
    case "cap-680p": return CL10C681JB8NNNC({ name })
    case "res-10k": return RC0603FR_0710KL({ name })
    case "res-15": return A_0603WAF150JT5E({ name })
    case "res-47": return A_0603WAF470JT5E({ name })
  }
}
