"""Connect reviewed catalog choices to their unmodified tsci imports."""
from pathlib import Path
import json
import re

project_dir = Path(__file__).resolve().parents[1]
catalog = json.loads((project_dir / "lib/generated/passive-catalog.json").read_text())
import_lines = []
cases = []
for catalog_key, part in catalog.items():
    supplier_number = f'"C{part["lcsc"]}"'
    matches = [import_path for import_path in (project_dir / "imports").glob("*.tsx")
               if supplier_number in import_path.read_text()]
    if len(matches) != 1:
        raise ValueError(f"Expected one genuine import for {catalog_key}: {matches}")
    import_path = matches[0]
    export_match = re.search(r"export const (\w+)", import_path.read_text())
    if not export_match:
        raise ValueError(f"Missing import export: {import_path}")
    export_name = export_match.group(1)
    import_lines.append(f'import {{ {export_name} }} from "../imports/{import_path.stem}"')
    cases.append(f'    case "{catalog_key}": return {export_name}({{ name }})')

source = '''// Generated by scripts/generate-passive-parts.py. Do not edit.
import type { ChipProps } from "@tscircuit/props"
import type { ReactElement } from "react"
'''
source += "\n".join(import_lines)
source += '''

export function getPassiveElement({ key, name }: { key: string; name: string }): ReactElement<ChipProps> | undefined {
  switch (key) {
'''
source += "\n".join(cases)
source += "\n  }\n}\n"
(project_dir / "lib/passive-parts.tsx").write_text(source)
